theme: jekyll-theme-cayman

description: Open Kinematics and Dynamics of Machinery
email: nimrobotics@gmail.com

github_username:  nimrobotics
twitter_username: nimrobotics
linkedin_username: nimrobotics

footer-links-active:
